version: "3.8"

services:

    # #################################
    # # Order: The Order microservice
    # #################################
    # order:
    #     build:
    #         context: ./
    #         dockerfile: order.Dockerfile      
    #     image: meifxng/order:1.0
    #     restart: always
    #     environment:
    #         dbURL: 'mysql://admin:password@database-1.cqnvz4nypbvo.us-east-1.rds.amazonaws.com/CME'
    #         PYTHONUNBUFFERED: 1
    #     ports:
    #         - "5000:5000"

    # ###############################################
    # # Inventory: The Inventory microservice
    # ###############################################
    # inventory:
    #     build:
    #         context: ./
    #         dockerfile: inventory.Dockerfile
    #     image: meifxng/inventory:1.0
    #     environment:
    #         dbURL: 'mysql://admin:password@database-1.cqnvz4nypbvo.us-east-1.rds.amazonaws.com/CME'
    #         PYTHONUNBUFFERED: 1
    #     ports:
    #         - "5001:5001"

    ###############################################
    # Fulfilment: The Fulfilment microservice
    ###############################################
    fulfilment:
        build:
            context: ./
            dockerfile: fulfilment.Dockerfile
        image: meifxng/fulfilment:1.0
        environment:
            FLASK_APP: fulfilment.py
            dbURL: 'mysql://admin:password@database-1.cqnvz4nypbvo.us-east-1.rds.amazonaws.com/CME'
            PYTHONUNBUFFERED: 1
        ports:
            - "5002:5002"